import { Inter } from 'next/font/google';
import './globals.css';
import { CustomThemeProvider } from '@/theme/ThemeContext';
import PersistProvider from '@/components/layout/PersistProvider';
import { GlobalProvider } from '@/context/commonContext';
import { SearchProvider } from '@/context/commonContext';
import Script from 'next/script';
const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // select what you need
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
   manifest: "/manifest.json",
  description: 'Generated by create next app',
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Script
          id="tawk-to"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
      var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
      (function(){
      var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
      s1.async=true;
      s1.src='https://embed.tawk.to/67f6a61c19e7691907e58ff9/1iodnho73';
      s1.charset='UTF-8';
      s1.setAttribute('crossorigin','*');
      s0.parentNode.insertBefore(s1,s0);
      })();
    `,
          }}
        />
        <SearchProvider>
          <GlobalProvider>
            <PersistProvider>
              <CustomThemeProvider>{children}</CustomThemeProvider>
            </PersistProvider>
          </GlobalProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
